// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJMxtMWe92BrRX7dR_oy5VDAYfGlBKGM',
    appId: '1:901650323147:web:8191c9e44d75f701bc2d4e',
    messagingSenderId: '901650323147',
    projectId: 'webrtcflutter20230507',
    authDomain: 'webrtcflutter20230507.firebaseapp.com',
    storageBucket: 'webrtcflutter20230507.appspot.com',
    measurementId: 'G-9DVZR6S0BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAk2vqSBelcwoyMYI3Qov3B7t4F6WlZGc',
    appId: '1:901650323147:android:6f8cbe7f29136262bc2d4e',
    messagingSenderId: '901650323147',
    projectId: 'webrtcflutter20230507',
    storageBucket: 'webrtcflutter20230507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTeT7lq-s7K3lnvMJSEDIOaR5d_MYCHs',
    appId: '1:901650323147:ios:3b5db10acf3e882dbc2d4e',
    messagingSenderId: '901650323147',
    projectId: 'webrtcflutter20230507',
    storageBucket: 'webrtcflutter20230507.appspot.com',
    iosClientId: '901650323147-se0vuv853gotvv2dc3f2llsnbj6b9g8f.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpTeT7lq-s7K3lnvMJSEDIOaR5d_MYCHs',
    appId: '1:901650323147:ios:21d24357352770edbc2d4e',
    messagingSenderId: '901650323147',
    projectId: 'webrtcflutter20230507',
    storageBucket: 'webrtcflutter20230507.appspot.com',
    iosClientId: '901650323147-3g28hvrk36occf7v3opb9v05bfn0odpm.apps.googleusercontent.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );
}
